freshen
creideiki/radio-free-san-andreas pull request #1
Opened 2020-05-29 17:35 UTC by tlby

* Adds metadata syntax to use one md5 as a base for another
 * Adds new md5s for recent releases
 * Adds track number to filenames
 * Updates assemble-songs.sh to cope with track numbers

2020-05-29 17:44 UTC, tlby commented
Not sure if you're interested in updates, but I had to tinker a little for the tool to work smoothly on later releases.

2020-05-29 20:13 UTC, creideiki requested changes
Thanks! I had no idea anyone was still interested in this code.

I have long since lost my original DVD copy of the game, but I tested on a Steam copy, and confirm that your changes make it work on that. So that's excellent, and I'm happy to include those changes, since anyone running this tool today would probably be doing it on a Steam copy.

Regarding the track numbers, I have no strong opinion either way on the functionality (they are easy to strip out of the file names and easy to re-add from the Vorbis metadata), but I do have two nits to pick regarding the implementation - see the review comments. If you make those changes I'll accept the pull request.

2020-05-29 20:13 UTC, creideiki commented on assemble-songs.sh
> +                rm -f "$enter" "$file" "$leave"
This leaves the DJ chatter intro and outro files, whereas the old code removed those as well. I would prefer it if this behaviour remained, since the intention of `assemble-songs.sh` is that a user who just wants to listen to everything should be able to run the script and be done, with no further processing required.

2020-05-29 20:13 UTC, creideiki commented on src/extract.cpp
> +               snprintf(filename, sizeof(filename), "%s/%s/%03d - %s.ogg",
I am not a fan of mixing C and C++ string functions like this. I would much prefer it if the pathname was constructed using a C++ `std::stringstream` (or any newer functionality that may exist today - I haven't actually written any serious C++ since C++03).

2020-05-29 20:46 UTC, tlby commented
Both great points.  I didn't want to end up accidentally using a feature that wasn't available in the era this was written.  `snprintf()` was definitely there, but yeah, it stands out like a sore thumb, thanks for an alternate suggestion.

2020-05-29 21:41 UTC, merged

2020-05-29 21:52 UTC, creideiki commented
Merged and released as version 0.2.3. Thanks!

2020-05-30 02:19 UTC, tlby commented
No, thank you for the meticulous track labeling that was done for this work in the first place.
⭐⭐⭐⭐⭐